[package]
name = "Firework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fork = "0.1.22"
libc = "0.2.147"
nfq = "0.2.5"
shmem = "0.2.0"
